import { Vehicle } from '@/components/VehicleCard'

export const fleetData: Vehicle[] = [
  {
    id: 'swift',
    name: 'Swift Dzire',
    category: 'car',
    capacity: 4,
    perKmRateAc: '12',
    perKmRateNonAc: '11',
    image: '/images/swift.png',
    tag: 'Most Economical',
  },
  {
    id: 'ertiga',
    name: 'Ertiga',
    category: 'car',
    capacity: 7,
    perKmRateAc: '15',
    perKmRateNonAc: '14',
    image: '/images/ertiga.png',
    tag: 'Family Favorite',
  },
  {
    id: 'tavera',
    name: 'Tavera',
    category: 'car',
    capacity: 7,
    perKmRateAc: '16',
    perKmRateNonAc: '15',
    image: '/images/tavera.png',
    tag: 'Rugged Explorer',
  },
  {
    id: 'innova',
    name: 'Innova',
    category: 'car',
    capacity: 7,
    perKmRateAc: '17',
    perKmRateNonAc: '16',
    image: '/images/innova-standard.png',
    tag: 'Highway Comfort',
  },
  {
    id: 'innova-crysta',
    name: 'Innova Crysta',
    category: 'car',
    capacity: 7,
    perKmRateAc: '20',
    perKmRateNonAc: '19',
    image: '/images/innova.png',
    tag: 'VIP Luxury',
  },
  {
    id: 'tempo-17',
    name: 'Tempo Traveller 17 Seater',
    category: 'van',
    capacity: 17,
    perKmRateAc: '30',
    perKmRateNonAc: '28',
    image: '/images/tempo.png',
    tag: 'Best for Groups',
  },
  {
    id: 'tempo-24',
    name: 'Tempo Traveller 24 Seater',
    category: 'van',
    capacity: 24,
    perKmRateAc: '35',
    perKmRateNonAc: '32',
    image: '/images/tempo.png',
    tag: 'Spacious Travel',
  },
  {
    id: 'mini-bus-20',
    name: 'Mini Bus 20 Seater',
    category: 'bus',
    capacity: 20,
    perKmRateAc: '40',
    image: '/images/bus.png',
    tag: 'Tour Groups',
  },
  {
    id: 'bus-56',
    name: 'Bus 56 Seater',
    category: 'bus',
    capacity: 56,
    perKmRateAc: '65',
    perKmRateNonAc: '45',
    image: '/images/bus.png',
    tag: 'Pilgrimage Special',
  },
]
