import { Vehicle } from '@/components/VehicleCard'

export const fleetData: Vehicle[] = [
  {
    id: 'mercedes-s',
    name: 'Mercedes-Benz S-Class',
    category: 'luxury',
    capacity: 4,
    ac: true,
    dailyRate: '12,000',
    perKmRate: '28',
    image: '/images/fleet-mercedes.jpg',
    tag: 'Most Premium',
  },
  {
    id: 'bmw-5',
    name: 'BMW 5 Series',
    category: 'luxury',
    capacity: 4,
    ac: true,
    dailyRate: '10,000',
    perKmRate: '24',
    image: '/images/fleet-suv.jpg',
    tag: 'Top Choice',
  },
  {
    id: 'honda-city',
    name: 'Honda City',
    category: 'sedan-suv',
    capacity: 4,
    ac: true,
    dailyRate: '3,500',
    perKmRate: '12',
    image: '/images/fleet-sedan.jpg',
  },
  {
    id: 'swift-dzire',
    name: 'Maruti Swift Dzire',
    category: 'sedan-suv',
    capacity: 4,
    ac: true,
    dailyRate: '2,800',
    perKmRate: '10',
    image: '/images/fleet-sedan.jpg',
  },
  {
    id: 'innova-crysta',
    name: 'Toyota Innova Crysta',
    category: 'sedan-suv',
    capacity: 7,
    ac: true,
    dailyRate: '5,500',
    perKmRate: '16',
    image: '/images/fleet-suv.jpg',
    tag: 'Best Seller',
  },
  {
    id: 'ertiga',
    name: 'Maruti Ertiga',
    category: 'sedan-suv',
    capacity: 6,
    ac: true,
    dailyRate: '4,000',
    perKmRate: '14',
    image: '/images/fleet-suv.jpg',
  },
  {
    id: 'tempo-traveller',
    name: 'Tempo Traveller (17 Seater)',
    category: 'bus',
    capacity: 17,
    ac: true,
    dailyRate: '8,000',
    perKmRate: '20',
    image: '/images/fleet-bus.jpg',
  },
  {
    id: 'mini-bus',
    name: 'Mini Bus (27 Seater)',
    category: 'bus',
    capacity: 27,
    ac: true,
    dailyRate: '12,000',
    perKmRate: '25',
    image: '/images/fleet-bus.jpg',
    tag: 'Group Travel',
  },
  {
    id: 'full-bus',
    name: 'Full Bus (50 Seater)',
    category: 'bus',
    capacity: 50,
    ac: false,
    dailyRate: '18,000',
    perKmRate: '30',
    image: '/images/fleet-bus.jpg',
  },
]
